# Generated by Django 3.1.14 on 2023-01-09 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_activate',
            field=models.BooleanField(default=False, verbose_name='email is_activate'),
        ),
    ]
