# Generated by Django 3.1.14 on 2023-01-12 10:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0001_initial'),
        ('users', '0002_user_email_activate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='title')),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.CharField(max_length=20, verbose_name='receiver')),
                ('place', models.CharField(max_length=120, verbose_name='specification address')),
                ('mobile', models.CharField(max_length=11, verbose_name='mobile_number')),
                ('telephone', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='tel')),
                ('email', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='email')),
                ('is_delete', models.BooleanField(default=False, verbose_name='is delete')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='city_address', to='areas.area', verbose_name='city_name')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='district_address', to='areas.area', verbose_name='district_name')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='province_address', to='areas.area', verbose_name='province_name')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address', to=settings.AUTH_USER_MODEL, verbose_name='user_address')),
            ],
            options={
                'verbose_name': 'address_for_receiver',
                'db_table': 'tb_address',
                'ordering': ['-update_at'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='default_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='users.address', verbose_name='default_address'),
        ),
    ]
