# Generated by Django 3.1.14 on 2023-01-14 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('key', models.CharField(max_length=100, verbose_name='category key')),
            ],
            options={
                'db_table': 'tb_content_category',
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Ad title')),
                ('url', models.URLField(max_length=300, verbose_name='content url')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='image')),
                ('text', models.TextField(blank=True, null=True, verbose_name='content')),
                ('sequence', models.IntegerField(verbose_name='sequence')),
                ('status', models.BooleanField(default=True, verbose_name='isShow')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='category', to='contents.contentcategory', verbose_name='category_id')),
            ],
            options={
                'db_table': 'tb_content',
            },
        ),
    ]
