# Generated by Django 3.1.14 on 2023-01-14 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Ad_title'),
        ),
        migrations.AlterField(
            model_name='content',
            name='url',
            field=models.URLField(max_length=300, verbose_name='content_url'),
        ),
        migrations.AlterField(
            model_name='contentcategory',
            name='key',
            field=models.CharField(max_length=100, verbose_name='category_key'),
        ),
    ]
