# Generated by Django 3.1.14 on 2023-01-14 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='brand')),
                ('logo', models.ImageField(upload_to='', verbose_name='logo_link')),
                ('first_letter', models.CharField(max_length=1, verbose_name='brandFirstLetter')),
            ],
            options={
                'db_table': 'tb_brand',
            },
        ),
        migrations.CreateModel(
            name='SKU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='sku_name')),
                ('caption', models.CharField(max_length=500, verbose_name='caption')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='price')),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='costPrice')),
                ('market_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='marketPrice')),
                ('stock', models.IntegerField(default=0, verbose_name='stock')),
                ('sales', models.IntegerField(default=0, verbose_name='sales')),
                ('comments', models.IntegerField(default=0, verbose_name='comments')),
                ('is_launched', models.BooleanField(default=True, verbose_name='isLaunched')),
                ('default_image_url', models.URLField(blank=True, default='', null=True, verbose_name='DefaultImageUrl')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='category', to='goods.goodscategory', verbose_name='category_id')),
            ],
            options={
                'db_table': 'tb_sku',
            },
        ),
        migrations.CreateModel(
            name='SPU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='product')),
                ('sales', models.IntegerField(default=0, verbose_name='sales')),
                ('comments', models.IntegerField(default=0, verbose_name='comments')),
                ('desc_detail', models.TextField(default='', verbose_name='detail')),
                ('desc_pack', models.TextField(default='', verbose_name='packInfo')),
                ('desc_service', models.TextField(default='', verbose_name='after_sales')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='brand', to='goods.brand', verbose_name='brand_id')),
                ('category1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='category1', to='goods.goodscategory', verbose_name='category1_id')),
                ('category2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='category2', to='goods.goodscategory', verbose_name='category2_id')),
                ('category3', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='category3', to='goods.goodscategory', verbose_name='category3_id')),
            ],
            options={
                'db_table': 'tb_spu',
            },
        ),
        migrations.AlterField(
            model_name='goodschannel',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='category_goods_channel', to='goods.goodscategory', verbose_name='channel_category'),
        ),
        migrations.CreateModel(
            name='SPUSpecification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='spu')),
                ('spu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specs', to='goods.spu', verbose_name='spu_id')),
            ],
            options={
                'db_table': 'tb_spu_specification',
            },
        ),
        migrations.CreateModel(
            name='SpecificationOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=300, verbose_name='optionValue')),
                ('spec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='goods.spuspecification', verbose_name='spec_id')),
            ],
            options={
                'db_table': 'tb_specification_option',
            },
        ),
        migrations.CreateModel(
            name='SKUSpecification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='SpecificationOption', to='goods.specificationoption', verbose_name='option_id')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sku', to='goods.sku', verbose_name='sku_id')),
                ('spec', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='SPUSpecification', to='goods.spuspecification', verbose_name='spec_id')),
            ],
            options={
                'db_table': 'tb_sku_specification',
            },
        ),
        migrations.CreateModel(
            name='SKUImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='imageUrl')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_sku', to='goods.sku', verbose_name='sku_id')),
            ],
            options={
                'db_table': 'tb_sku_image',
            },
        ),
        migrations.AddField(
            model_name='sku',
            name='spu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spu', to='goods.spu', verbose_name='spu_id'),
        ),
    ]
